import type {
  AnimationPlan,
  Animation,
  Action,
  CreateTextAction,
  CreateShapeAction,
} from "../schema/types.js";
import { expandPreset } from "../presets/index.js";
import { wrapIIFE, indent, comment, joinCode } from "./utils.js";
import { generateTargeting } from "./targeting.js";
import { generateStagger } from "./stagger.js";
import { generateKeyframes } from "./keyframes.js";
import { generateEffects } from "./effects.js";
import { generateCreateText } from "./create-text.js";
import { generateCreateShape } from "./create-shape.js";

// Type guards for action dispatch
function isCreateTextAction(action: Action): action is CreateTextAction {
  return "type" in action && action.type === "create_text";
}

function isCreateShapeAction(action: Action): action is CreateShapeAction {
  return "type" in action && action.type === "create_shape";
}

function isLegacyAnimation(action: Action): action is Animation {
  return !("type" in action) || action.type === undefined;
}

/**
 * Generate ExtendScript for a single legacy animation block.
 */
function generateAnimation(anim: Animation, animIdx: number): string {
  const expanded = expandPreset(anim);
  const parts: string[] = [];

  parts.push(comment(`--- Animation ${animIdx + 1} ---`));
  parts.push("");

  // Layer targeting
  parts.push(comment("Layer Targeting"));
  parts.push(generateTargeting(expanded.target));
  parts.push("");

  // Per-layer loop
  parts.push("for (var i = 0; i < layers.length; i++) {");

  const loopBody: string[] = [];
  loopBody.push("var layer = layers[i];");
  loopBody.push("var layerIndex = i;");

  // Stagger
  if (expanded.stagger) {
    loopBody.push("");
    loopBody.push(comment("Stagger delay"));
    loopBody.push(generateStagger(expanded.stagger));
  } else {
    loopBody.push("var staggerDelay = 0;");
  }

  // Keyframes for each property animation
  if (expanded.properties && expanded.properties.length > 0) {
    const easing = expanded.easing ?? "easeOutCubic";
    const duration = expanded.duration ?? 0.5;

    for (let pi = 0; pi < expanded.properties.length; pi++) {
      loopBody.push("");
      loopBody.push(comment(`Property: ${expanded.properties[pi].property}`));
      loopBody.push(
        generateKeyframes({
          propAnim: expanded.properties[pi],
          easing,
          duration,
          animIndex: pi,
          delay: expanded.delay,
          startAt: expanded.startAt,
          anchorPoint: expanded.anchorPoint,
        })
      );
    }
  }

  // Effects
  if (expanded.effects && expanded.effects.length > 0) {
    loopBody.push("");
    loopBody.push(comment("Effects"));
    loopBody.push(generateEffects(expanded.effects));
  }

  parts.push(indent(loopBody.join("\n")));
  parts.push("}");
  parts.push("");

  return parts.join("\n");
}

/**
 * Generate a complete ExtendScript string from an animation plan.
 */
export function generate(plan: AnimationPlan): string {
  const bodyParts: string[] = [];

  // Header comment
  bodyParts.push(comment(`Generated by Spline v1.0 — "${plan.name}"`));
  bodyParts.push("");

  // Comp reference + validation
  bodyParts.push("var comp = app.project.activeItem;");
  bodyParts.push("if (!(comp instanceof CompItem)) {");
  bodyParts.push('    alert("Spline: Please select a composition.");');
  bodyParts.push("    return;");
  bodyParts.push("}");
  bodyParts.push("");

  // Undo group
  bodyParts.push('app.beginUndoGroup("Spline Animation");');
  bodyParts.push("");

  // Build unified action list: actions[] first, then legacy animations[]
  var actionIndex = 0;

  if (plan.actions && plan.actions.length > 0) {
    for (var ai = 0; ai < plan.actions.length; ai++) {
      const action = plan.actions[ai];

      if (isCreateTextAction(action)) {
        bodyParts.push(generateCreateText(action, actionIndex));
        bodyParts.push("");
      } else if (isCreateShapeAction(action)) {
        bodyParts.push(generateCreateShape(action, actionIndex));
        bodyParts.push("");
      } else if (isLegacyAnimation(action)) {
        bodyParts.push(generateAnimation(action, actionIndex));
      }

      actionIndex++;
    }
  }

  if (plan.animations && plan.animations.length > 0) {
    for (var animIdx = 0; animIdx < plan.animations.length; animIdx++) {
      bodyParts.push(generateAnimation(plan.animations[animIdx], actionIndex));
      actionIndex++;
    }
  }

  // End undo group
  bodyParts.push("app.endUndoGroup();");

  return wrapIIFE(indent(bodyParts.join("\n")));
}
